/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Saves a user's email to the waitlist and returns a confirmation
 * @summary Join the early access waitlist
 */
export const JoinWaitlistBody = zod.object({
  email: zod.string().email(),
});

export const JoinWaitlistResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  alreadyRegistered: zod.boolean(),
});
